In [1]:
import tkinter as tk
from tkinter import ttk
from tkinter import messagebox
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score
from nltk.sentiment.vader import SentimentIntensityAnalyzer
import nltk

In [2]:
nltk.download('vader_lexicon')

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     C:\Users\hi\AppData\Roaming\nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

True

In [3]:
app_df=pd.read_csv(r"C:\Users\hi\Downloads\Play Store Data.csv")

In [4]:
app_df.head(10)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
5,Paper flowers instructions,ART_AND_DESIGN,4.4,167,5.6M,"50,000+",Free,0,Everyone,Art & Design,"March 26, 2017",1.0,2.3 and up
6,Smoke Effect Photo Maker - Smoke Editor,ART_AND_DESIGN,3.8,178,19M,"50,000+",Free,0,Everyone,Art & Design,"April 26, 2018",1.1,4.0.3 and up
7,Infinite Painter,ART_AND_DESIGN,4.1,36815,29M,"1,000,000+",Free,0,Everyone,Art & Design,"June 14, 2018",6.1.61.1,4.2 and up
8,Garden Coloring Book,ART_AND_DESIGN,4.4,13791,33M,"1,000,000+",Free,0,Everyone,Art & Design,"September 20, 2017",2.9.2,3.0 and up
9,Kids Paint Free - Drawing Fun,ART_AND_DESIGN,4.7,121,3.1M,"10,000+",Free,0,Everyone,Art & Design;Creativity,"July 3, 2018",2.8,4.0.3 and up

In [5]:
app_df.tail(10)

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
10831,payermonstationnement.fr,MAPS_AND_NAVIGATION,NaN,38,9.8M,"5,000+",Free,0,Everyone,Maps & Navigation,"June 13, 2018",2.0.148.0,4.0 and up
10832,FR Tides,WEATHER,3.8,1195,582k,"100,000+",Free,0,Everyone,Weather,"February 16, 2014",6.0,2.1 and up
10833,Chemin (fr),BOOKS_AND_REFERENCE,4.8,44,619k,"1,000+",Free,0,Everyone,Books & Reference,"March 23, 2014",0.8,2.2 and up
10834,FR Calculator,FAMILY,4.0,7,2.6M,500+,Free,0,Everyone,Education,"June 18, 2017",1.0.0,4.1 and up
10835,FR Forms,BUSINESS,NaN,0,9.6M,10+,Free,0,Everyone,Business,"September 29, 2016",1.1.5,4.0 and up
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [6]:
app_df.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver'],
      dtype='str')

In [7]:
app_df.describe()

            Rating
count  9367.000000
mean      4.193338
std       0.537431
min       1.000000
25%       4.000000
50%       4.300000
75%       4.500000
max      19.000000

In [8]:
app_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  str
 1   Category        10841 non-null  str
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  str
 4   Size            10841 non-null  str
 5   Installs        10841 non-null  str
 6   Type            10840 non-null  str
 7   Price           10841 non-null  str
 8   Content Rating  10840 non-null  str
 9   Genres          10841 non-null  str
 10  Last Updated    10841 non-null  str
 11  Current Ver     10833 non-null  str
 12  Android Ver     10838 non-null  str
dtypes: float64(1), str(12)
memory usage: 1.1 MB

In [9]:
app_df.duplicated().sum()

np.int64(483)

In [10]:
app_df=app_df.drop_duplicates()

In [11]:
app_df.duplicated().sum()

np.int64(0)

In [12]:
app_df.isnull().sum()

App                  0
Category             0
Rating            1465
Reviews              0
Size                 0
Installs             0
Type                 1
Price                0
Content Rating       1
Genres               0
Last Updated         0
Current Ver          8
Android Ver          3
dtype: int64

In [13]:
app_df.info()

<class 'pandas.DataFrame'>
Index: 10358 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10358 non-null  str
 1   Category        10358 non-null  str
 2   Rating          8893 non-null   float64
 3   Reviews         10358 non-null  str
 4   Size            10358 non-null  str
 5   Installs        10358 non-null  str
 6   Type            10357 non-null  str
 7   Price           10358 non-null  str
 8   Content Rating  10357 non-null  str
 9   Genres          10358 non-null  str
 10  Last Updated    10358 non-null  str
 11  Current Ver     10350 non-null  str
 12  Android Ver     10355 non-null  str
dtypes: float64(1), str(12)
memory usage: 1.1 MB

In [14]:
app_df['App'] = app_df['App'].str.strip()

In [15]:
app_df['App'] = app_df['App'].str.capitalize()

In [16]:
app_df['App'].duplicated().sum()

np.int64(719)

In [17]:
app_df = app_df.drop_duplicates(subset='App', keep='first')

In [18]:
app_df['Rating']=app_df['Rating'].fillna(app_df['Rating'].mode()[0])

In [19]:
app_df['Content Rating']=app_df['Content Rating'].fillna(app_df['Content Rating'].mode()[0])

In [20]:
app_df['Current Ver']=app_df['Current Ver'].fillna(app_df['Current Ver'].mode()[0])

In [21]:
app_df['Android Ver']=app_df['Android Ver'].fillna(app_df['Android Ver'].mode()[0])

In [22]:
app_df=app_df.dropna(subset=['Type'])

In [23]:
def convert_size(size):
    if pd.isna(size):
        return None
    size = str(size)

    if size.endswith('M'):
        return float(size[:-1])

    elif size.endswith('k'):
        return float(size[:-1]) / 1024

    else:
        return None

app_df['Size'] = app_df['Size'].apply(convert_size)

In [24]:
app_df['Size'].head()

0    19.0
1    14.0
2     8.7
3    25.0
4     2.8
Name: Size, dtype: float64

In [25]:
app_df['Size']=app_df['Size'].fillna(app_df['Size'].median())

In [26]:
app_df['Installs']=app_df['Installs'].str.replace('+','',regex=False)
app_df['Installs']=app_df['Installs'].str.replace(',','',regex=False)

In [27]:
app_df=app_df[app_df['Installs']!='Free']

In [28]:
app_df['Installs']=app_df['Installs'].astype(int)

In [29]:
app_df['Installs'].unique()

array([     10000,     500000,    5000000,   50000000,     100000,
            50000,    1000000,   10000000,       5000,  100000000,
       1000000000,       1000,  500000000,         50,        100,
              500,         10,          1,          5,          0])

In [30]:
app_df['Log_installs']=np.log(app_df['Installs'])

C:\Users\hi\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

In [31]:
app_df['Price']=app_df['Price'].str.replace('$','',regex=False).astype(float)

In [32]:
app_df['Price'].unique()

array([  0.  ,   4.99,   3.99,   6.99,   1.49,   2.99,   7.99,   5.99,
         3.49,   1.99,   9.99,   7.49,   0.99,   9.  ,   5.49,  10.  ,
        24.99,  11.99,  79.99,  16.99,  14.99,   1.  ,  29.99,  12.99,
         2.49,  10.99,   1.5 ,  19.99,  15.99,  33.99,  74.99,  39.99,
         3.95,   4.49,   1.7 ,   8.99,   2.  ,   3.88,  25.99, 399.99,
        17.99, 400.  ,   3.02,   1.76,   4.84,   4.77,   1.61,   2.5 ,
         1.59,   6.49,   1.29,   5.  ,  13.99, 299.99, 379.99,  37.99,
        18.99,  19.9 ,   8.49,   1.75,  14.  ,   4.85,  46.99, 109.99,
       154.99,   3.08,   2.59,   4.8 ,   1.96,  19.4 ,   3.9 ,   4.59,
        15.46,   3.04,   4.29,   2.6 ,   3.28,   4.6 ,  28.99,   2.95,
         2.9 ,   1.97, 200.  ,  89.99,   2.56,  30.99,   3.61,   1.26,
         1.2 ,   1.04])

In [33]:
app_df['Revenue']=app_df['Price']*app_df['Installs']

In [34]:
print(app_df)

                                                     App             Category  \
0         Photo editor & candy camera & grid & scrapbook       ART_AND_DESIGN
1                                    Coloring book moana       ART_AND_DESIGN
2      U launcher lite – free live cool themes, hide ...       ART_AND_DESIGN
3                                  Sketch - draw & paint       ART_AND_DESIGN
4                  Pixel draw - number art coloring book       ART_AND_DESIGN
...                                                  ...                  ...
10836                                   Sya9a maroc - fr               FAMILY
10837                   Fr. mike schmitz audio teachings               FAMILY
10838                             Parkinson exercices fr              MEDICAL
10839                      The scp foundation db fr nn5n  BOOKS_AND_REFERENCE
10840      Ihoroscope - 2018 daily horoscope & astrology            LIFESTYLE

       Rating Reviews  Size  Installs  Type  Price Content Rating  \
0         4.1     159  19.0     10000  Free    0.0       Everyone
1         3.9     967  14.0    500000  Free    0.0       Everyone
2         4.7   87510   8.7   5000000  Free    0.0       Everyone
3         4.5  215644  25.0  50000000  Free    0.0           Teen
4         4.3     967   2.8    100000  Free    0.0       Everyone
...       ...     ...   ...       ...   ...    ...            ...
10836     4.5      38  53.0      5000  Free    0.0       Everyone
10837     5.0       4   3.6       100  Free    0.0       Everyone
10838     4.3       3   9.5      1000  Free    0.0       Everyone
10839     4.5     114  12.0      1000  Free    0.0     Mature 17+
10840     4.5  398307  19.0  10000000  Free    0.0       Everyone

                          Genres      Last Updated         Current Ver  \
0                   Art & Design   January 7, 2018               1.0.0
1      Art & Design;Pretend Play  January 15, 2018               2.0.0
2                   Art & Design    August 1, 2018               1.2.4
3                   Art & Design      June 8, 2018  Varies with device
4        Art & Design;Creativity     June 20, 2018                 1.1
...                          ...               ...                 ...
10836                  Education     July 25, 2017                1.48
10837                  Education      July 6, 2018                 1.0
10838                    Medical  January 20, 2017                 1.0
10839          Books & Reference  January 19, 2015  Varies with device
10840                  Lifestyle     July 25, 2018  Varies with device

              Android Ver  Log_installs  Revenue
0            4.0.3 and up      9.210340      0.0
1            4.0.3 and up     13.122363      0.0
2            4.0.3 and up     15.424948      0.0
3              4.2 and up     17.727534      0.0
4              4.4 and up     11.512925      0.0
...                   ...           ...      ...
10836          4.1 and up      8.517193      0.0
10837          4.1 and up      4.605170      0.0
10838          2.2 and up      6.907755      0.0
10839  Varies with device      6.907755      0.0
10840  Varies with device     16.118096      0.0

[9637 rows x 15 columns]

In [35]:
app_df['Reviews']=app_df['Reviews'].astype(int)

In [36]:
app_df=app_df[app_df['Rating']<=5]

In [37]:
app_df['Rating_Category']=pd.cut(app_df['Rating'],bins=[0,2,3,4,5],labels=['Poor','Average','Good','Excellent'])

In [38]:
app_df.isnull().sum()

App                0
Category           0
Rating             0
Reviews            0
Size               0
Installs           0
Type               0
Price              0
Content Rating     0
Genres             0
Last Updated       0
Current Ver        0
Android Ver        0
Log_installs       0
Revenue            0
Rating_Category    0
dtype: int64

In [39]:
print(app_df)

                                                     App             Category  \
0         Photo editor & candy camera & grid & scrapbook       ART_AND_DESIGN
1                                    Coloring book moana       ART_AND_DESIGN
2      U launcher lite – free live cool themes, hide ...       ART_AND_DESIGN
3                                  Sketch - draw & paint       ART_AND_DESIGN
4                  Pixel draw - number art coloring book       ART_AND_DESIGN
...                                                  ...                  ...
10836                                   Sya9a maroc - fr               FAMILY
10837                   Fr. mike schmitz audio teachings               FAMILY
10838                             Parkinson exercices fr              MEDICAL
10839                      The scp foundation db fr nn5n  BOOKS_AND_REFERENCE
10840      Ihoroscope - 2018 daily horoscope & astrology            LIFESTYLE

       Rating  Reviews  Size  Installs  Type  Price Content Rating  \
0         4.1      159  19.0     10000  Free    0.0       Everyone
1         3.9      967  14.0    500000  Free    0.0       Everyone
2         4.7    87510   8.7   5000000  Free    0.0       Everyone
3         4.5   215644  25.0  50000000  Free    0.0           Teen
4         4.3      967   2.8    100000  Free    0.0       Everyone
...       ...      ...   ...       ...   ...    ...            ...
10836     4.5       38  53.0      5000  Free    0.0       Everyone
10837     5.0        4   3.6       100  Free    0.0       Everyone
10838     4.3        3   9.5      1000  Free    0.0       Everyone
10839     4.5      114  12.0      1000  Free    0.0     Mature 17+
10840     4.5   398307  19.0  10000000  Free    0.0       Everyone

                          Genres      Last Updated         Current Ver  \
0                   Art & Design   January 7, 2018               1.0.0
1      Art & Design;Pretend Play  January 15, 2018               2.0.0
2                   Art & Design    August 1, 2018               1.2.4
3                   Art & Design      June 8, 2018  Varies with device
4        Art & Design;Creativity     June 20, 2018                 1.1
...                          ...               ...                 ...
10836                  Education     July 25, 2017                1.48
10837                  Education      July 6, 2018                 1.0
10838                    Medical  January 20, 2017                 1.0
10839          Books & Reference  January 19, 2015  Varies with device
10840                  Lifestyle     July 25, 2018  Varies with device

              Android Ver  Log_installs  Revenue Rating_Category
0            4.0.3 and up      9.210340      0.0       Excellent
1            4.0.3 and up     13.122363      0.0            Good
2            4.0.3 and up     15.424948      0.0       Excellent
3              4.2 and up     17.727534      0.0       Excellent
4              4.4 and up     11.512925      0.0       Excellent
...                   ...           ...      ...             ...
10836          4.1 and up      8.517193      0.0       Excellent
10837          4.1 and up      4.605170      0.0       Excellent
10838          2.2 and up      6.907755      0.0       Excellent
10839  Varies with device      6.907755      0.0       Excellent
10840  Varies with device     16.118096      0.0       Excellent

[9637 rows x 16 columns]

In [40]:
app_df['Rating_Category']=pd.cut(app_df['Rating'],bins=[0,2,3,4,5],labels=['Poor','Average','Good','Excellent'])

In [41]:
def Installs_category(Installs):
    if Installs < 50000:
        return "Low"
    elif Installs < 1000000:
        return "Average"
    else:
        return "High"

        
app_df['Install_category']=app_df['Installs'].apply(Installs_category)

In [42]:
app_df['Installs']=app_df['Installs'].astype(int)

In [43]:
app_df['Installs'].unique()

array([     10000,     500000,    5000000,   50000000,     100000,
            50000,    1000000,   10000000,       5000,  100000000,
       1000000000,       1000,  500000000,         50,        100,
              500,         10,          1,          5,          0])

In [44]:
app_df.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver', 'Log_installs', 'Revenue', 'Rating_Category',
       'Install_category'],
      dtype='str')

In [45]:
review_df=pd.read_csv(r"C:\Users\hi\Downloads\User Reviews.csv")

In [46]:
review_df.head(10)

,App,Translated_Review,Sentiment,Sentiment_Polarity,Sentiment_Subjectivity
0,10 Best Foods for You,I like eat delicious food. That's I'm cooking ...,Positive,1.00,0.533333
1,10 Best Foods for You,This help eating healthy exercise regular basis,Positive,0.25,0.288462
2,10 Best Foods for You,NaN,NaN,NaN,NaN
3,10 Best Foods for You,Works great especially going grocery store,Positive,0.40,0.875000
4,10 Best Foods for You,Best idea us,Positive,1.00,0.300000
5,10 Best Foods for You,Best way,Positive,1.00,0.300000
6,10 Best Foods for You,Amazing,Positive,0.60,0.900000
7,10 Best Foods for You,NaN,NaN,NaN,NaN
8,10 Best Foods for You,"Looking forward app,",Neutral,0.00,0.000000
9,10 Best Foods for You,It helpful site ! It help foods get !,Neutral,0.00,0.000000

In [47]:
review_df=review_df.dropna(subset=['Translated_Review','Sentiment','Sentiment_Polarity','Sentiment_Subjectivity'],how='all')

In [48]:
review_df.isnull().sum()

App                       0
Translated_Review         5
Sentiment                 0
Sentiment_Polarity        0
Sentiment_Subjectivity    0
dtype: int64

In [49]:
review_df=review_df.dropna(subset=['Translated_Review'])

In [50]:
sia = SentimentIntensityAnalyzer()

In [51]:
review_df['Sentiment_Score'] = review_df['Translated_Review'].apply(
    lambda x: sia.polarity_scores(str(x))['compound']
)

In [52]:
review_df

,App,Translated_Review,Sentiment,Sentiment_Polarity,Sentiment_Subjectivity,Sentiment_Score
0,10 Best Foods for You,I like eat delicious food. That's I'm cooking ...,Positive,1.000000,0.533333,0.9531
1,10 Best Foods for You,This help eating healthy exercise regular basis,Positive,0.250000,0.288462,0.6597
3,10 Best Foods for You,Works great especially going grocery store,Positive,0.400000,0.875000,0.6249
4,10 Best Foods for You,Best idea us,Positive,1.000000,0.300000,0.6369
5,10 Best Foods for You,Best way,Positive,1.000000,0.300000,0.6369
...,...,...,...,...,...,...
64222,Housing-Real Estate & Property,Most ads older many agents ..not much owner po...,Positive,0.173333,0.486667,-0.6486
64223,Housing-Real Estate & Property,"If photos posted portal load, fit purpose. I'm...",Positive,0.225000,0.447222,0.7430
64226,Housing-Real Estate & Property,"Dumb app, I wanted post property rent give opt...",Negative,-0.287500,0.250000,-0.7269
64227,Housing-Real Estate & Property,I property business got link SMS happy perform...,Positive,0.800000,1.000000,0.7783
64230,Housing-Real Estate & Property,"Useless app, I searched flats kondapur, Hydera...",Negative,-0.316667,0.400000,-0.0829

In [53]:
merged_df=pd.merge(app_df,review_df,on='App',how='inner')

In [54]:
merged_df.isnull().sum()

App                       0
Category                  0
Rating                    0
Reviews                   0
Size                      0
Installs                  0
Type                      0
Price                     0
Content Rating            0
Genres                    0
Last Updated              0
Current Ver               0
Android Ver               0
Log_installs              0
Revenue                   0
Rating_Category           0
Install_category          0
Translated_Review         0
Sentiment                 0
Sentiment_Polarity        0
Sentiment_Subjectivity    0
Sentiment_Score           0
dtype: int64

In [55]:
review_df.to_csv("googleplaystore_review_cleaned.csv",index=False)

In [56]:
merged_df.to_csv("googleplaystore_merged_cleaned.csv",index=False)

In [57]:
app_df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Log_installs,Revenue,Rating_Category,Install_category
0,Photo editor & candy camera & grid & scrapbook,ART_AND_DESIGN,4.1,159,19.0,10000,Free,0.0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up,9.210340,0.0,Excellent,Low
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14.0,500000,Free,0.0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up,13.122363,0.0,Good,Average
2,"U launcher lite – free live cool themes, hide ...",ART_AND_DESIGN,4.7,87510,8.7,5000000,Free,0.0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up,15.424948,0.0,Excellent,High
3,Sketch - draw & paint,ART_AND_DESIGN,4.5,215644,25.0,50000000,Free,0.0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up,17.727534,0.0,Excellent,High
4,Pixel draw - number art coloring book,ART_AND_DESIGN,4.3,967,2.8,100000,Free,0.0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up,11.512925,0.0,Excellent,Average
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,Sya9a maroc - fr,FAMILY,4.5,38,53.0,5000,Free,0.0,Everyone,Education,"July 25, 2017",1.48,4.1 and up,8.517193,0.0,Excellent,Low
10837,Fr. mike schmitz audio teachings,FAMILY,5.0,4,3.6,100,Free,0.0,Everyone,Education,"July 6, 2018",1.0,4.1 and up,4.605170,0.0,Excellent,Low
10838,Parkinson exercices fr,MEDICAL,4.3,3,9.5,1000,Free,0.0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up,6.907755,0.0,Excellent,Low
10839,The scp foundation db fr nn5n,BOOKS_AND_REFERENCE,4.5,114,12.0,1000,Free,0.0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device,6.907755,0.0,Excellent,Low
10840,Ihoroscope - 2018 daily horoscope & astrology,LIFESTYLE,4.5,398307,19.0,10000000,Free,0.0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device,16.118096,0.0,Excellent,High

In [58]:
review_df['App'].duplicated().sum()

np.int64(36562)

In [59]:
app_df['App'].isna().sum()
review_df['App'].isna().sum()

np.int64(0)

In [60]:
print("Duplicate app names:", app_df['App'].duplicated().sum())
print("Total rows:", len(app_df))
print("Unique apps:", app_df['App'].nunique())

Duplicate app names: 0
Total rows: 9637
Unique apps: 9637

In [61]:
app_df['App'] = app_df['App'].str.strip()
review_df['App'] = review_df['App'].str.strip()

In [62]:
app_df['App'].duplicated().sum()

np.int64(0)

In [63]:
print("Duplicate app names:", app_df['App'].duplicated().sum())
print("Unique apps:", app_df['App'].nunique())
print("Total rows:", len(app_df))

Duplicate app names: 0
Unique apps: 9637
Total rows: 9637

In [64]:
app_df['App'].duplicated().sum()

np.int64(0)

In [65]:
review_df['App'].duplicated().sum()

np.int64(36562)

In [66]:
app_df.to_csv("app_df_cleaned5.csv",index=False)

In [67]:
app_df = app_df.drop_duplicates(subset=['App'], keep='first')

In [68]:
app_df['Last Updated'] = pd.to_datetime(app_df['Last Updated'])
app_df['Month'] = app_df['Last Updated'].dt.to_period('M').astype(str)

In [69]:
##app_df['Year_Month'] = app_df['Last Updated'].dt.to_period('M').astype(str)

In [70]:
##app_df['Month_Name'] = app_df['Last Updated'].dt.strftime('%B')

In [71]:
app_df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver,Log_installs,Revenue,Rating_Category,Install_category,Month
0,Photo editor & candy camera & grid & scrapbook,ART_AND_DESIGN,4.1,159,19.0,10000,Free,0.0,Everyone,Art & Design,2018-01-07,1.0.0,4.0.3 and up,9.210340,0.0,Excellent,Low,2018-01
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14.0,500000,Free,0.0,Everyone,Art & Design;Pretend Play,2018-01-15,2.0.0,4.0.3 and up,13.122363,0.0,Good,Average,2018-01
2,"U launcher lite – free live cool themes, hide ...",ART_AND_DESIGN,4.7,87510,8.7,5000000,Free,0.0,Everyone,Art & Design,2018-08-01,1.2.4,4.0.3 and up,15.424948,0.0,Excellent,High,2018-08
3,Sketch - draw & paint,ART_AND_DESIGN,4.5,215644,25.0,50000000,Free,0.0,Teen,Art & Design,2018-06-08,Varies with device,4.2 and up,17.727534,0.0,Excellent,High,2018-06
4,Pixel draw - number art coloring book,ART_AND_DESIGN,4.3,967,2.8,100000,Free,0.0,Everyone,Art & Design;Creativity,2018-06-20,1.1,4.4 and up,11.512925,0.0,Excellent,Average,2018-06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,Sya9a maroc - fr,FAMILY,4.5,38,53.0,5000,Free,0.0,Everyone,Education,2017-07-25,1.48,4.1 and up,8.517193,0.0,Excellent,Low,2017-07
10837,Fr. mike schmitz audio teachings,FAMILY,5.0,4,3.6,100,Free,0.0,Everyone,Education,2018-07-06,1.0,4.1 and up,4.605170,0.0,Excellent,Low,2018-07
10838,Parkinson exercices fr,MEDICAL,4.3,3,9.5,1000,Free,0.0,Everyone,Medical,2017-01-20,1.0,2.2 and up,6.907755,0.0,Excellent,Low,2017-01
10839,The scp foundation db fr nn5n,BOOKS_AND_REFERENCE,4.5,114,12.0,1000,Free,0.0,Mature 17+,Books & Reference,2015-01-19,Varies with device,Varies with device,6.907755,0.0,Excellent,Low,2015-01
10840,Ihoroscope - 2018 daily horoscope & astrology,LIFESTYLE,4.5,398307,19.0,10000000,Free,0.0,Everyone,Lifestyle,2018-07-25,Varies with device,Varies with device,16.118096,0.0,Excellent,High,2018-07

In [72]:
filtered_app_df = app_df[
    (app_df['Reviews'] > 500) &
    (~app_df['App'].str.contains('S', case=False, na=False)) &
    (~app_df['App'].str.startswith(('X', 'Y', 'Z'), na=False)) &
    (app_df['Category'].str.startswith(('B', 'C', 'E'), na=False))
].copy()

In [73]:
filtered_app_df['Category_Display'] = filtered_app_df['Category'].replace({
    'BEAUTY': 'सौंदर्य',
    'BUSINESS': 'வணிகம்',
    'DATING': 'Partnersuche'
})

In [74]:
filtered_app_df['Last Updated'] = pd.to_datetime(
    filtered_app_df['Last Updated']
)

In [75]:
filtered_app_df['Month'] = (
    filtered_app_df['Last Updated']
    .dt.to_period('M')
    .astype(str)
)

In [76]:
monthly_installs = (
    filtered_app_df
    .groupby(['Month', 'Category_Display'], as_index=False)['Installs']
    .sum()
)

In [77]:
monthly_installs = monthly_installs.sort_values(
    ['Category_Display', 'Month']
)

In [78]:
monthly_installs['MoM_Growth'] = (
    monthly_installs
    .groupby('Category_Display')['Installs']    .pct_change()
)

In [79]:
monthly_installs['Highlight_Installs'] = monthly_installs.apply(
    lambda row: row['Installs']
    if row['MoM_Growth'] > 0.20
    else None,
    axis=1
)

In [80]:
monthly_installs.head(20)

      Month     Category_Display   Installs  MoM_Growth  Highlight_Installs
5   2014-10  BOOKS_AND_REFERENCE     500000         NaN                 NaN
6   2014-11  BOOKS_AND_REFERENCE    5000000    9.000000           5000000.0
10  2015-07  BOOKS_AND_REFERENCE   10000000    1.000000          10000000.0
18  2016-06  BOOKS_AND_REFERENCE      60000   -0.994000                 NaN
21  2016-08  BOOKS_AND_REFERENCE     100000    0.666667            100000.0
27  2017-02  BOOKS_AND_REFERENCE     100000    0.000000                 NaN
29  2017-04  BOOKS_AND_REFERENCE    1000000    9.000000           1000000.0
31  2017-05  BOOKS_AND_REFERENCE     100000   -0.900000                 NaN
32  2017-07  BOOKS_AND_REFERENCE     100000    0.000000                 NaN
33  2017-08  BOOKS_AND_REFERENCE   10010000   99.100000          10010000.0
38  2017-11  BOOKS_AND_REFERENCE    2000000   -0.800200                 NaN
49  2018-04  BOOKS_AND_REFERENCE    1050000   -0.475000                 NaN
51  2018-05  BOOKS_AND_REFERENCE   40600000   37.666667          40600000.0
58  2018-06  BOOKS_AND_REFERENCE   47100000    0.160099                 NaN
64  2018-07  BOOKS_AND_REFERENCE  101600000    1.157113         101600000.0
72  2018-08  BOOKS_AND_REFERENCE  110050000    0.083169                 NaN
28  2017-03               COMICS     100000         NaN                 NaN
52  2018-05               COMICS     100000    0.000000                 NaN
65  2018-07               COMICS    6000000   59.000000           6000000.0
73  2018-08               COMICS    5050000   -0.158333                 NaN

In [81]:
monthly_installs.to_csv(
    'monthly_installs.csv',
    index=False
)

In [82]:
monthly_installs.isnull().sum()

Month                  0
Category_Display       0
Installs               0
MoM_Growth             8
Highlight_Installs    45
dtype: int64

In [83]:
monthly_installs[monthly_installs['MoM_Growth'] > 0.20][
    ['Month', 'Category_Display', 'Installs', 'MoM_Growth', 'Highlight_Installs']
]

      Month     Category_Display    Installs  MoM_Growth  Highlight_Installs
6   2014-11  BOOKS_AND_REFERENCE     5000000    9.000000        5.000000e+06
10  2015-07  BOOKS_AND_REFERENCE    10000000    1.000000        1.000000e+07
21  2016-08  BOOKS_AND_REFERENCE      100000    0.666667        1.000000e+05
29  2017-04  BOOKS_AND_REFERENCE     1000000    9.000000        1.000000e+06
33  2017-08  BOOKS_AND_REFERENCE    10010000   99.100000        1.001000e+07
51  2018-05  BOOKS_AND_REFERENCE    40600000   37.666667        4.060000e+07
64  2018-07  BOOKS_AND_REFERENCE   101600000    1.157113        1.016000e+08
65  2018-07               COMICS     6000000   59.000000        6.000000e+06
3   2014-07        COMMUNICATION    10000000   99.000000        1.000000e+07
11  2015-08        COMMUNICATION     2000000    1.000000        2.000000e+06
22  2016-09        COMMUNICATION     1000000    8.090909        1.000000e+06
25  2016-11        COMMUNICATION    11000000   10.000000        1.100000e+07
39  2017-11        COMMUNICATION     5000000   99.000000        5.000000e+06
43  2018-01        COMMUNICATION    16000000    2.200000        1.600000e+07
53  2018-05        COMMUNICATION     5000000    4.000000        5.000000e+06
59  2018-06        COMMUNICATION    11100000    1.220000        1.110000e+07
66  2018-07        COMMUNICATION   315730000   27.444144        3.157300e+08
74  2018-08        COMMUNICATION  1298510000    3.112723        1.298510e+09
7   2015-01            EDUCATION      100000    9.000000        1.000000e+05
9   2015-06            EDUCATION     1000000    9.000000        1.000000e+06
34  2017-08            EDUCATION     1000000    9.000000        1.000000e+06
41  2017-12            EDUCATION     3000000    2.000000        3.000000e+06
67  2018-07            EDUCATION    29600000   13.095238        2.960000e+07
17  2016-04        ENTERTAINMENT    10000000    9.000000        1.000000e+07
44  2018-01        ENTERTAINMENT    20000000    1.000000        2.000000e+07
60  2018-06        ENTERTAINMENT    21100000    2.516667        2.110000e+07
68  2018-07        ENTERTAINMENT   380800000   17.047393        3.808000e+08
61  2018-06               EVENTS      500000   49.000000        5.000000e+05
69  2018-07               EVENTS     1100000    1.200000        1.100000e+06
62  2018-06              सौंदर्य     1000000  199.000000        1.000000e+06
16  2016-03               வணிகம்     1000000   99.000000        1.000000e+06
42  2017-12               வணிகம்     1001000    1.002000        1.001000e+06
63  2018-06               வணிகம்    15200000  151.000000        1.520000e+07
78  2018-08               வணிகம்   115100000    8.922414        1.151000e+08

In [84]:
monthly_installs['Month_Sort'] = (
    pd.to_datetime(monthly_installs['Month']).dt.year * 100
    + pd.to_datetime(monthly_installs['Month']).dt.month
)

In [85]:
filtered_stacked_df = app_df[
    (app_df['Rating'] >= 4.2) &
    (app_df['Reviews'] > 1000) &
    (app_df['Size'] >= 20) &
    (app_df['Size'] <= 80) &
    (~app_df['App'].str.contains(r'\d', regex=True, na=False)) &
    (app_df['Category'].str.startswith(('T', 'P'), na=False))
].copy()

In [86]:
filtered_stacked_df['Category_Display'] = (
    filtered_stacked_df['Category'].replace({
        'TRAVEL & LOCAL': 'Voyage et local',
        'PRODUCTIVITY': 'Productividad',
        'PHOTOGRAPHY': '写真'
    })
)

In [87]:
filtered_stacked_df['Category_Display'] = filtered_stacked_df['Category_Display'].replace({
    'TRAVEL_AND_LOCAL': 'Voyage et local'
})

In [88]:
filtered_stacked_df['Last Updated'] = pd.to_datetime(
    filtered_stacked_df['Last Updated']
)

filtered_stacked_df['Month'] = (
    filtered_stacked_df['Last Updated']
    .dt.to_period('M')
    .astype(str)
)

In [89]:
stacked_monthly = (
    filtered_stacked_df
    .groupby(['Month', 'Category_Display'], as_index=False)['Installs']
    .sum()
)

In [90]:
stacked_monthly = stacked_monthly.sort_values(
    ['Category_Display', 'Month']
)

stacked_monthly['MoM_Growth'] = (
    stacked_monthly
    .groupby('Category_Display')['Installs']
    .pct_change()
)

In [91]:
stacked_monthly['Growth_Flag'] = (
    stacked_monthly['MoM_Growth'] > 0.25
)

In [92]:
growth_months = (
    stacked_monthly
    .groupby('Month')['Growth_Flag']
    .any()
    .reset_index(name='Growth_Month')
)

In [93]:
stacked_monthly = stacked_monthly.merge(
    growth_months,
    on='Month',
    how='left'
)

In [94]:
stacked_monthly['Cumulative_Installs'] = (
    stacked_monthly
    .groupby('Category_Display')['Installs']
    .cumsum()
)

In [95]:
stacked_monthly.to_csv('stacked_monthly.csv',index=False)

In [96]:
app_df['Last Updated'] = pd.to_datetime(app_df['Last Updated'], errors='coerce')

In [97]:
jan_df = app_df[app_df['Last Updated'].dt.month == 1].copy()

In [98]:
filtered_df = jan_df[(jan_df['Rating'] >= 4.0) &(jan_df['Size'] >= 10)].copy()

In [99]:
category_summary = (filtered_df.groupby('Category').
    agg(Average_Rating=('Rating', 'mean'),
        Total_Reviews=('Reviews', 'sum'),
        Total_Installs=('Installs', 'sum')
    )
    .reset_index()
)

In [100]:
top10_categories = (
    category_summary
    .sort_values('Total_Installs', ascending=False)
    .head(10)
)

In [101]:
top10_categories['Average_Rating'] = top10_categories['Average_Rating'].round(2)

top10_categories

            Category  Average_Rating  Total_Reviews  Total_Installs
11              GAME            4.31        2449381       120691010
23            SPORTS            4.38        1988575       120626100
8             FAMILY            4.41        2892479        97696180
24             TOOLS            4.29         331603        72011110
25  TRAVEL_AND_LOCAL            4.12          17075        51001000
6      ENTERTAINMENT            4.30         869111        21000000
18   PERSONALIZATION            4.44         156004        15061000
20      PRODUCTIVITY            4.42         221779        11610005
3      COMMUNICATION            4.30         367312        11502000
19       PHOTOGRAPHY            4.20         563737        10501000

In [103]:
app_df.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',
       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',
       'Android Ver', 'Log_installs', 'Revenue', 'Rating_Category',
       'Install_category', 'Month'],
      dtype='str')

In [104]:
review_df.columns

Index(['App', 'Translated_Review', 'Sentiment', 'Sentiment_Polarity',
       'Sentiment_Subjectivity', 'Sentiment_Score'],
      dtype='str')